chain-specs/paseo.plain.json, chain-specs/paseo.raw.json
https://telemetry.polkadot.io/#list/0x74300973617e2936e22d46e94fee5016a1a514747ae108277b770d02b47d37d9
=> chain-specs: add default telemetry url

chain-specs/paseo.plain.json, chain-specs/paseo.raw.json
Fixed a typo in the node-id in the bootnode string.
=> Add RadiumBlock Paseo bootnode changes

chain-specs/paseo.plain.json, chain-specs/paseo.raw.json
Just a follow up of my previous PR #16 
Thank you
=> Follow up of previous PR #16

chain-specs/paseo.plain.json, chain-specs/paseo.raw.json
Add stake plus bootnodes for paseo
=> Add stake plus bootnodes for paseo

chain-specs/paseo.plain.json, chain-specs/paseo.raw.json
replaces https://github.com/paseo-network/runtimes/pull/21
=> add metaspan bootnodes

.github/build-runtime.yaml
=> Adding build runtime GH action to create deterministic runtime

.github/workflows/build-runtime.yaml
=> Fix build runtime pipeline

chain-specs/asset-hub-paseo.plain.json, chain-specs/asset-hub-paseo.raw.json
Plase consider adding RadiumBlock bootnodes for Assethub Paseo
=> Add RadiumBlock bootnodes to Assethub Paseo chain spec

.github/ISSUE_TEMPLATE/runtime-upgrade---upgrade-title-version-.md
Update Runtime Upgrade issue template
=> Update Runtime Upgrade issue template

scripts/apply_runtime_patch.py, scripts/create_runtime_patch.sh, scripts/replacements_config.json, scripts/revert_unwanted_changes.py, scripts/test_replacements.py
- Support for RegExp 
- Minor tweaks
=> Improvements on runtime patcher

integration-tests/emulated/tests/bridges/bridge-hub-paseo/src/tests/snowbridge.rs
Hey @raynaudoe! Thanks for upgrading the Snowbridge config. :) I updated the integration tests. Once your branch `release/1.2.8-runtime` compiles I will double check these tests also pass.
=> Updates Snowbridge integration tests

chain-spec-generator/src/system_parachains_specs.rs
Reverts paseo-network/runtimes#150
=> Revert "fix: correct local spec ids"

relay/paseo/src/genesis_config_presets.rs
Amend Paseo's genesis config.
It seems that on syncing the code with the fellowship we've lost a few of our own changes.
=> refactor(paseo): amend genesis config

system-parachains/asset-hub-paseo/primitives/src/lib.rs
Correct some wrong naming in comments.
=> fix(docs): asset hub comments

system-parachains/asset-hub-paseo/src/lib.rs, system-parachains/asset-hub-paseo/tests/tests.rs, system-parachains/asset-hub-paseo/tests/weight_trader.rs
Clean unnecessary tests and further amends usage of ed keys for ah.
=> refactor(ah): further key type corrections & clean unnecessary tests

system-parachains/bridge-hub-paseo/tests/snowbridge.rs
The chain ID was set to `1` (Ethereum mainnet) instead of `11155111` (Ethereum Sepolia testnet) in some places.
=> Fixes Snowbridge tests

Cargo.lock, relay/paseo/Cargo.toml, relay/paseo/constants/src/lib.rs, relay/paseo/src/lib.rs, relay/paseo/src/xcm_config.rs
Includes PASSETHUB as a trusted teleported of the relay.
:link: [zboto Link](https://app.clickup.com/t/86997nh6x)
=> refactor(xcm): PAssetHub is trusted TP

Cargo.lock, system-parachains/constants/src/paseo.rs
:link: [zboto Link](https://app.clickup.com/t/86999wa4d)
=> v1.5.1 - fixes

relay/paseo/src/xcm_config.rs
:link: [zboto Link](https://app.clickup.com/t/8699jqc1m)
=> Adding PassetHub 1111 as trusted teleporter

relay/paseo/src/governance/tracks.rs, relay/paseo/src/lib.rs, system-parachains/asset-hub-paseo/src/lib.rs
:link: [zboto Link](https://app.clickup.com/t/8699mmr96)
=> v1.6.0 - fixes

.github/workflows/build-release.yaml, .github/workflows/comment-trigger.yml, .github/workflows/generate-chain-specs.yaml
:link: [zboto Link](https://app.clickup.com/t/869a0d1mv)
=> Rename CI_PAT according to usage

relay/paseo/src/lib.rs
:link: [zboto Link](https://app.clickup.com/t/869a0dk5v)
=> Use polkadot_runtime_common with benchmarking features

README.md
This PR provides an initial view on the differences between Paseo testnet and the production environments like Kusama and Polkadot.
The main focus in showing in a quick glance which features are available on each platform and how some of the costs of the present features compare.
The idea is to extend and maintain this information over time.
:link: [zboto Link](https://app.clickup.com/t/869ac66gk)
=> docs: testnet<>prod runtime diff
