- chain-specs/paseo.plain.json
- chain-specs/paseo.raw.json
Dear team, 
Please consider this request to add the bootnodes available from Gatotech as part of the IBP collective.
These endpoints were tested using a modified `paseo.json` chainspec (bootnodes removed), and passing the `--bootnodes` flag manually, like below:
```
polkadot --no-hardware-benchmarks --no-mdns --chain paseo.json --bootnodes "/dns/boot.gatotech.network/tcp/33400/p2p/12D3KooWEvz5Ygv3MhCUNTVQbUTVhzhvf4KKcNoe5M5YbVLPBeeW"
polkadot --no-hardware-benchmarks --no-mdns --chain paseo.json --bootnodes "/dns/boot.gatotech.network/tcp/35400/wss/p2p/12D3KooWEvz5Ygv3MhCUNTVQbUTVhzhvf4KKcNoe5M5YbVLPBeeW"
```
Many thanks!
Best regards!!
Milos
> add bootnodes by Gatotech

- chain-specs/paseo.plain.json
- chain-specs/paseo.raw.json
Adds Helikon boot node into the chain spec files.
To test:
```
./polkadot --chain ./spec/paseo.raw.json --tmp --reserved-only --reserved-nodes "/dns/boot-node.helikon.io/tcp/10020/p2p/12D3KooWBetfzZpf6tGihKrqCo5z854Ub4ZNAUUTRT6eYHNh7FYi"
./polkadot --chain ./spec/paseo.raw.json --tmp --reserved-only --reserved-nodes "/dns/boot-node.helikon.io/tcp/10022/wss/p2p/12D3KooWBetfzZpf6tGihKrqCo5z854Ub4ZNAUUTRT6eYHNh7FYi"
```
> Helikon boot node

- chain-specs/paseo.plain.json
- chain-specs/paseo.raw.json
Add RadiumBlock boot node to the chain spec files
Please test using:
`./polkadot --chain ./paseo.raw.json --reserved-only --reserved-nodes "/dns/paseo-bootnode.radiumblock.com/tcp/30335/wss/p2p/12D3KooWeayZC8zag4Qrb4GosSn65MmfVZztRPMaBdgZnQqXRo"`
`./polkadot --chain ./paseo.raw.json --reserved-only --reserved-nodes "/dns/paseo-bootnode.radiumblock.com/tcp/30333/p2p/12D3KooWADeaC8zag4Qrb4GosSn65MmfVZztRPMaBdgZnQqXRo"`
> Add RadiumBlock bootnode for Paseo

- chain-specs/paseo.plain.json
- chain-specs/paseo.raw.json
Tested with:
`./polkadot --chain ./paseo.raw.json --reserved-only --reserved-nodes "/dns/paseo-boot-ng.dwellir.com/tcp/30354/p2p/12D3KooWBLLFKDGBxCwq3QmU3YwWKXUx953WwprRshJQicYu4Cfr"`
`./polkadot --chain ./paseo.raw.json --reserved-only --reserved-nodes "/dns/paseo-boot-ng.dwellir.com/tcp/443/wss/p2p/12D3KooWBLLFKDGBxCwq3QmU3YwWKXUx953WwprRshJQicYu4Cfr"`
> Add Dwellir bootnode for Paseo

- relay/paseo/src/lib.rs
This change gets rid of the lease offset configured in `pallet-slots`.
> Remove lease offset

- chain-spec-generator/src/relay_chain_specs.rs
To get Paseo Local to onboard parachains requires new eras to start and they cannot start by default without a second validator.
This adds Bob to the Alice validator in the same way as Rococo Local has.
> Add Bob to get Paseo-Local to onboard parachains

- chain-spec-generator/src/relay_chain_specs.rs
Ran into some issues while testing out Paseo Local. These changes are ONLY in the chain-spec-generator and do not change the paseo spec at all, but it does change (fix) the paseo-local which before would fail due to having the Alice key in the endowment twice.
- Cleanup: Remove duplicated functions
- Cleanup: Require endowed accounts instead of defaulting
- Bug: Fix issue with duplicate endowments due to root key being in the endowed accounts
Note: I thought about fixing without the filter, either by putting the filter or short list in the `paseo_local_genesis` and/or just throwing an error if it happens, but ended up with the path of make the error not happen. Happy to swap it up if someone has a strong opinion on one of the other paths.
- `cargo build`
- …
> Fixed issue with duplicate endowment on Paseo Local + cleanup

- chain-specs/paseo.plain.json
- chain-specs/paseo.raw.json
https://github.com/paseo-network/runtimes/pull/17
seems like my bootnode is not anymore in chain-spec
> readd rotko bootnodes

- chain-specs/asset-hub-paseo.plain.json
- chain-specs/asset-hub-paseo.raw.json
Adding asset-hub-paseo Dwellir bootnodes.
Verified by running a node using `--reserved-only` and `--reserved-nodes`.
> Added asset-hub-paseo Dwellir bootnodes

- relay/paseo/Cargo.toml
- system-parachains/asset-hub-paseo/Cargo.toml
Even though the goal should be and is releasing every runtime at the same time, that is not happening at the moment.
Which creates some version mismatches regarding the runtimes and their crates.
> fix(crates): Individual crate versioning.

- system-parachains/bridge-hub-paseo/src/bridge_to_ethereum_config.rs
- system-parachains/bridge-hub-paseo/src/lib.rs
The Ethereum fork versions were replaced with the mainnet versions, instead of Sepolia's values.
> Fix Snowbridge fork versions

- README.md
- chain-spec-generator/src/relay_chain_specs.rs
- relay/paseo/src/genesis_config_presets.rs
- relay/paseo/src/lib.rs
These changes address some feedback on the base PR and removed a migration that it is not necessary to be run.
> Remove corrupted ledger migration

- chain-spec-generator/src/system_parachains_specs.rs
When running `pop up parachain` with the latest paseo release (`v1.3.1`) I was getting an issue generating the chain-spec. Comparing the old one generated (`v1.2.6`) with the new one I noticed the difference was with the id:
```
"name": "Asset Hub Paseo Local",
"id": "asset-hub-paseo-local"
```
vs
```
“name": "Paseo Asset Hub Local",
"id": "paseo-asset-hub-local",
```
Fixed to use `asset-hub-paseo-local`.
> fix: system parachain chain spec generator

- chain-spec-generator/src/system_parachains_specs.rs
In line with the changes in #149 this corrects the spec ids for the rest of the local specs
> fix: correct local spec ids

- relay/paseo/src/lib.rs
The removed migration doesn't need to be applied.
> chore: remove CancelAuction migration

- integration-tests/emulated/chains/parachains/coretime/coretime-paseo/src/lib.rs
- integration-tests/emulated/chains/relays/paseo/src/lib.rs
- integration-tests/emulated/tests/coretime/coretime-paseo/src/lib.rs
- integration-tests/emulated/tests/coretime/coretime-paseo/src/tests/coretime_interface.rs
- integration-tests/emulated/tests/coretime/coretime-paseo/src/tests/teleport.rs
Fixes build for coretime integration tests
> fix: coretime integration tests

- Cargo.lock
The `main` branch was not building due to an outdated dependency if using rustc >= 1.80. This PR fixes that.
> Fix broken dependency

- chain-spec-generator/src/relay_chain_specs.rs
- chain-spec-generator/src/system_parachains_specs.rs
Use available genesis presets in the chain spec generator
> refactor(spec-generator): use genesis presets

- system-parachains/asset-hub-paseo/src/genesis_config_presets.rs
Fix "wrong" key type usage and some naming.
> refactor(asset-hub): amend ah genesis config

- system-parachains/bridge-hub-paseo/src/bridge_to_kusama_config.rs
Easy redefinition of `UniversalLocation` to fix the build of bridge-hub
> fix(bridge-hub): Proper `UniversalLocation` definition

- .github/workflows/build-release-manual.yaml
- .github/workflows/build-release.yaml
- .github/workflows/generate-chain-specs.yaml
- chain-spec-generator/Cargo.toml
- chain-spec-generator/src/common.rs
- chain-spec-generator/src/main.rs
- chain-spec-generator/src/system_parachains_specs.rs
> feat(spec-generator): introduce collectives in spec generator

- relay/paseo/src/genesis_config_presets.rs
I'm not 100% sure this is correct as I'm not sure if we want it to be 3 on local and dev.
Also it changes it for regenerating the paseo mainnet genesis, but that would only happen if restarting the network.
Closes: #199
> Update the scheduling lookahead to be 3 for dev and local genesis to match Polkadot

- relay/paseo/src/genesis_config_presets.rs
This PR syncs the host configuration for Paseo genesis such that it matches the configuration we are running live.
Ensuring a better experience for those users which run paseo locally for development and/or testing.
The change has a simple companion unit test that locks the configuration at this point and should help us ensure that we don't change it by accident.
> refactor: sync paseo host config

- .chopsticks/coretime.yml
- relay/paseo/src/lib.rs
- system-parachains/coretime-paseo/src/coretime.rs
This PR changes the implementation of `pallet_broker::PriceAdapter` to fix the end price and the target price for every sale.
While we keep the auction model, where there is downward pressure - we remove how the previous sale performance would affect to the subsequent sale prices.
This should ease the DevEx around coretime in testnet.
:link: [zboto Link](https://app.clickup.com/t/8699mvy3w)
> chore: fix coretime price curve

- Cargo.lock
- Cargo.toml
- system-parachains/asset-hub-paseo/tests/tests.rs
- system-parachains/bridge-hub-paseo/src/xcm_config.rs
- system-parachains/bridge-hub-paseo/tests/tests.rs
- system-parachains/collectives-paseo/src/xcm_config.rs
- system-parachains/collectives-paseo/tests/tests.rs
- system-parachains/constants/src/paseo.rs
- system-parachains/coretime-paseo/src/tests.rs
- system-parachains/coretime-paseo/src/xcm_config.rs
- system-parachains/people-paseo/src/tests.rs
- system-parachains/people-paseo/src/xcm_config.rs
This PR updates release 1.7.1 to account for the AHM migration that already took place on Paseo in the systems chain code.
Mainly, all the system chains recognize AH as their authority now. Paseo itself and AssetHub are excluded from this PR as there'll be a dedicated PR for them
:link: [zboto Link](https://app.clickup.com/t/869ah7at5)
> release: 1.7.1+ah-migration/system-chains
